version: '{build}'
branches:
  only:
  - master
  - appveyor
#---------------------------------#
#       build configuration       #
#---------------------------------#

image: Visual Studio 2019
configuration: Release
build:
  project: HelloWorld.sln
  parallel: true
  verbosity: minimal
platform:
  - x64
  - Win32


#after_build:
#  - cmd: move %APPVEYOR_BUILD_FOLDER%\%PLATFORM%\Release\HelloWorld.exe %APPVEYOR_BUILD_FOLDER%\HelloWorld
#  - cmd: 7z a HelloWorld.zip HelloWorld\HelloWorld.exe

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#  
#artifacts:
#- path: HelloWorld.zip
#  name: HelloWorld
