version: 0.0.0.'{build}'
branches:
  only:
  - master
  - appveyor
#---------------------------------#
#       build configuration       #
#---------------------------------#

image: Visual Studio 2019
configuration: Release
build:
  project: HelloWorld.sln
  parallel: true
  verbosity: minimal
platform:
  - x64
  - Win32


#after_build:
#  - cmd: move %APPVEYOR_BUILD_FOLDER%\%PLATFORM%\Release\HelloWorld.exe %APPVEYOR_BUILD_FOLDER%\HelloWorld
#  - cmd: 7z a HelloWorld.zip HelloWorld\HelloWorld.exe

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#  
#artifacts:
#- path: HelloWorld.zip
#  name: HelloWorld

after_build:
  - cmd: move %APPVEYOR_BUILD_FOLDER%\%PLATFORM%\Release\HelloWorld.exe %APPVEYOR_BUILD_FOLDER%\HelloWorld
  - cmd: 7z a HelloWorld.zip HelloWorld\HelloWorld.exe
  
artifacts:
    # файлы-артефакты нужно предварительно явно указать в данной секции
    # в терминологии AppVeyor это называется "push artifacts"
    - path: HelloWorld\HelloWorld.exe

deploy:
    # выкладываем tagged-коммиты на GitHub Releases:
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    provider: GitHub

    auth_token:
        secure: /j11FkWAb7Eqt5/aJAAV0JiviX97gHHBf9tUFSV9qQLfPD1amrfpGSDhcPngtkB5

    artifact: package_name
    force_update: true

    on:
        appveyor_repo_tag: true