version: '{build}'
branches:
  only:
  - master
  - appveyor
image: Visual Studio 2019
configuration: Release
build:
  project: HelloWorld.sln
  parallel: true
  verbosity: minimal
platform:
  - x64
  - Win32
