version: 0.0.0.'{build}'
branches:
  only:
  - master
  - appveyor
#---------------------------------#
#       build configuration       #
#---------------------------------#

image: Visual Studio 2019
configuration: Release
build:
  project: HelloWorld.sln
  parallel: true
  verbosity: minimal
platform:
  - x64
  - x86


#after_build:
#  - cmd: move %APPVEYOR_BUILD_FOLDER%\%PLATFORM%\Release\HelloWorld.exe %APPVEYOR_BUILD_FOLDER%\HelloWorld
#  - cmd: 7z a HelloWorld.zip HelloWorld\HelloWorld.exe

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
#artifacts:
#- path: HelloWorld.zip
#  name: HelloWorld

after_build:
  - cmd: move %APPVEYOR_BUILD_FOLDER%\%PLATFORM%\Release\HelloWorld.exe %APPVEYOR_BUILD_FOLDER%\HelloWorld
  - cmd: 7z a HelloWorld_%PLATFORM%.zip HelloWorld\%PLATFORM%\HelloWorld.exe

#artifacts:
    # файлы-артефакты нужно предварительно явно указать в данной секции
    # в терминологии AppVeyor это называется "push artifacts"
#    - path: HelloWorld\HelloWorld.exe

deploy:
  on:
    branch: master                 # релизы только из ветки master
    appveyor_repo_tag: true        # только если имеется прикрепленный tag

  provider: GitHub                         # выкладываем на GitHub Releases
  description: 'Bump version to $(APPVEYOR_REPO_TAG_NAME).$(APPVEYOR_BUILD_NUMBER)' # tag как имя релиза

  auth_token:
    secure: /j11FkWAb7Eqt5/aJAAV0JiviX97gHHBf9tUFSV9qQLfPD1amrfpGSDhcPngtkB5 # токен, зашифрованный на сайте appveyor.ci

  artifact: /.*\.zip/ # регулярное выражение, описывающее все артефакты данного релиза
  force_update: true  # перезаписывать артефакты, если файл с таким именем уже имеется
  draft: false
  prerelease: false
