version: $(APPVEYOR_REPO_TAG_NAME).{build}
branches:
  only:
  - master
  - appveyor
#---------------------------------#
#       build configuration       #
#---------------------------------#
image: Visual Studio 2019
configuration: Release
build:
  project: HelloWorld.sln
  parallel: true
  verbosity: minimal
platform:
  - x64
  - x86

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
after_build:
  - cmd: 7z a HelloWorld_%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\%PLATFORM%\Release\HelloWorld.exe

artifacts:
  path: /*.zip
  name: HelloWorld

deploy:
  description: 'Version to $(APPVEYOR_REPO_TAG_NAME).$(APPVEYOR_BUILD_NUMBER)' # tag как имя релиза
  provider: GitHub                         # выкладываем на GitHub Releases
  auth_token:
    secure: /j11FkWAb7Eqt5/aJAAV0JiviX97gHHBf9tUFSV9qQLfPD1amrfpGSDhcPngtkB5 # токен
  artifact: HelloWorld
  draft: false        # Отключаем черновой выпуск
  prerelease: false   # Отключаем пометку предрелиз
  force_update: true  # перезаписывать артефакты, если файл с таким именем уже имеется

  on:
    branch: master                # релизы только из ветки master
    appveyor_repo_tag: true       # только если имеется прикрепленный tag
